---
name: Build Docker images

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Set metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            gitea.stump.wtf/joestump/reader
          tags: |
            type=raw,value=latest,enable={{ is_default_branch }}
            type=ref,event=pr
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Gitea
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: gitea.stump.wtf
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GIT_AUTH_TOKEN }}
      - name: Build and push
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          github-token: ${{ secrets.GIT_AUTH_TOKEN }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
